Demo.CONFIG = [{
    id: 1,
    text: "布局"
}, {
    id: 2,
    text: "基础控件"
}, {
    id: 3,
    text: "实例控件"
}, {
    id: 4,
    text: "详细控件"
}, {
    id: 5,
    text: "通用组件"
}, {
    pId: 1,
    text: "bi.center_adapt",
    value: "demo.center_adapt"
}, {
    pId: 1,
    text: "bi.vertical_adapt",
    value: "demo.vertical_adapt"
}, {
    pId: 1,
    text: "bi.horizontal_adapt",
    value: "demo.horizontal_adapt"
}, {
    pId: 1,
    text: "bi.horizontal_auto",
    value: "demo.horizontal_auto"
}, {
    pId: 1,
    text: "bi.horizontal_float",
    value: "demo.horizontal_float"
}, {
    pId: 1,
    text: "bi.left_right_vertical_adapt",
    value: "demo.left_right_vertical_adapt"
}, {
    pId: 1,
    text: "bi.center",
    value: "demo.center_layout"
}, {
    pId: 1,
    text: "bi.float_center",
    value: "demo.float_center"
}, {
    pId: 1,
    text: "bi.vertical",
    value: "demo.vertical"
}, {
    pId: 1,
    text: "bi.horizontal",
    value: "demo.horizontal"
}, {
    pId: 1,
    text: "bi.border",
    value: "demo.border"
}, {
    pId: 1,
    text: "bi.left, bi.right",
    value: "demo.flow"
}, {
    pId: 1,
    text: "bi.inline",
    value: "demo.inline"
}, {
    pId: 1,
    text: "bi.htape",
    value: "demo.htape"
}, {
    pId: 1,
    text: "bi.vtape",
    value: "demo.vtape"
}, {
    pId: 1,
    text: "bi.grid",
    value: "demo.grid"
}, {
    pId: 1,
    text: "bi.table",
    value: "demo.table_layout"
}, {
    pId: 1,
    text: "bi.td",
    value: "demo.td"
}];