export interface _var {
    MAX: number;
    MIN: number;
    EVENT_RESPONSE_TIME: number;
    zIndex_layer: number;
    zIndex_popover: number;
    zIndex_popup: number;
    zIndex_masker: number;
    zIndex_tip: number;
    emptyStr: string;
    emptyFn: Function;
    empty: null,
    Key: {
        48: string;
        49: string;
        50: string;
        51: string;
        52: string;
        53: string;
        54: string;
        55: string;
        56: string;
        57: string;
        65: string;
        66: string;
        67: string;
        68: string;
        69: string;
        70: string;
        71: string;
        72: string;
        73: string;
        74: string;
        75: string;
        76: string;
        77: string;
        78: string;
        79: string;
        80: string;
        81: string;
        82: string;
        83: string;
        84: string;
        85: string;
        86: string;
        87: string;
        88: string;
        89: string;
        90: string;
        96: string;
        97: string;
        98: string;
        99: string;
        100: string;
        101: string;
        102: string;
        103: string;
        104: string;
        105: string;
        106: string;
        107: string;
        109: string;
        110: string;
        111: string;
    },
    KeyCode: {
        BACKSPACE: number;
        COMMA: number;
        DELETE: number;
        DOWN: number;
        END: number;
        ENTER: number;
        ESCAPE: number;
        HOME: number;
        LEFT: number;
        NUMPAD_ADD: number;
        NUMPAD_DECIMAL: number;
        NUMPAD_DIVIDE: number;
        NUMPAD_ENTER: number;
        NUMPAD_MULTIPLY: number;
        NUMPAD_SUBTRACT: number;
        PAGE_DOWN: number;
        PAGE_UP: number;
        PERIOD: number;
        RIGHT: number;
        SPACE: number;
        TAB: number;
        UP: number;
    },
    Status: {
        SUCCESS: number;
        WRONG: number;
        START: number;
        END: number;
        WAITING: number;
        READY: number;
        RUNNING: number;
        OUTOFBOUNDS: number;
        NULL: number;
    },
    Direction: {
        Top: string;
        Bottom: string;
        Left: string;
        Right: string;
        Custom: string;
    },
    Axis: {
        Vertical: string;
        Horizontal: string;
    },
    Selection: {
        Default: number;
        None: number;
        Single: number;
        Multi: number;
        All: number;
    },
    HorizontalAlign: {
        Left: string;
        Right: string;
        Center: string;
        Stretch: string;
    },
    VerticalAlign: {
        Middle: string;
        Top: string;
        Bottom: string;
        Stretch: string;
    },
    StartOfWeek: number;
    BlankSplitChar: string;
}
