Demo.BASE_CONFIG = [{
    id: 2,
    text: "基础控件"
}, {
    pId: 2,
    id: 5,
    text: "组合"
}, {
    pId: 2,
    id: 8,
    text: "tree"
}, {
    pId: 2,
    id: 7,
    text: "button"
}, {
    pId: 2,
    id: 9,
    text: "listitem"
}, {
    pId: 2,
    id: 10,
    text: "editor"
}, {
    pId: 2,
    text: "bi.canvas",
    value: "demo.canvas"
}, {
    pId: 2,
    text: "bi.label",
    value: "demo.label"
}, {
    pId: 2,
    text: "bi.collection",
    value: "demo.collection"
}, {
    pId: 2,
    text: "bi.farbtastic",
    value: "demo.farbtastic"
}, {
    pId: 2,
    text: "bi.formulaeditor",
    value: "demo.formulaeditor"
}, {
    pId: 2,
    text: "bi.message",
    value: "demo.message"
}, {
    pId: 2,
    text: "bi.grid_view",
    value: "demo.grid_view"
}, {
    pId: 2,
    id: 6,
    text: "弹出层"
}, {
    pId: 2,
    text: "bi.pager",
    value: "demo.pager"
}, {
    pId: 2,
    text: "bi.svg",
    value: "demo.svg"
}, {
    pId: 2,
    text: "bi.table",
    value: "demo.table"
}, {
    pId: 5,
    text: "bi.combo",
    value: "demo.combo"
}, {
    pId: 5,
    text: "bi.expander",
    value: "demo.expander"
}, {
    pId: 5,
    text: "bi.group_button",
    value: "demo.group_button"
}, {
    pId: 5,
    text: "bi.group_combo",
    value: "demo.group_combo"
}, {
    pId: 5,
    text: "bi.loader",
    value: "demo.loader"
}, {
    pId: 5,
    text: "bi.navigation",
    value: "demo.navigation"
}, {
    pId: 5,
    text: "bi.searcher",
    value: "demo.searcher"
}, {
    pId: 5,
    text: "bi.switcher",
    value: "demo.switcher"
}, {
    pId: 5,
    text: "bi.tab",
    value: "demo.tab"
}, {
    pId: 5,
    text: "bi.tree_button",
    value: "demo.tree_button"
}, {
    pId: 6,
    text: "bi.layer_float_box",
    value: "demo.layer_float_box"
}, {
    pId: 6,
    text: "bi.layer_popup",
    value: "demo.layer_popup"
}, {
    pId: 6,
    text: "bi.layer_scroll",
    value: "demo.layer_scroll"
}, {
    pId: 6,
    text: "bi.layer_searcher",
    value: "demo.layer_searcher"
}, {
    pId: 7,
    text: "bi.icon_button",
    value: "demo.icon_button"
}, {
    pId: 7,
    text: "bi.image_button",
    value: "demo.image_button"
}, {
    pId: 7,
    text: "bi.button",
    value: "demo.button"
}, {
    pId: 7,
    text: "bi.text_button",
    value: "demo.text_button"
}, {
    pId: 8,
    text: "bi.treeview",
    value: "demo.treeview"
}, {
    pId: 8,
    text: "bi.synctree",
    value: "demo.synctree"
}, {
    pId: 8,
    text: "bi.parttree",
    value: "demo.parttree"
}, {
    pId: 8,
    text: "bi.customtree",
    value: "demo.customtree"
}, {
    pId: 9,
    text: "bi.list_items",
    value: "demo.list_items"
}, {
    pId: 10,
    text: "bi.code_editor",
    value: "demo.code_editor"
}, {
    pId: 10,
    text: "bi.editor",
    value: "demo.editor"
}, {
    pId: 10,
    text: "bi.multifile_editor",
    value: "demo.multifile_editor"
}, {
    pId: 10,
    text: "bi.text_area_editor",
    value: "demo.text_area_editor"
}];