Demo.BASE_CONFIG = [{
    id: 2,
    text: "基础控件",
    open: true,
}, {
    pId: 2,
    text: "bi.label",
    value: "demo.label"
}, {
    pId: 2,
    text: "title提示",
    value: "demo.title"
}, {
    pId: 2,
    text: "气泡提示",
    value: "demo.bubble"
}, {
    pId: 2,
    text: "toast提示",
    value: "demo.toast"
}, {
    pId: 2,
    text: "message提示",
    value: "demo.message"
}, {
    pId: 2,
    id: 201,
    text: "button"
}, {
    pId: 201,
    text: "bi.button",
    value: "demo.button"
}, {
    pId: 201,
    text: "bi.text_button",
    value: "demo.text_button"
}, {
    pId: 201,
    text: "bi.icon_button",
    value: "demo.icon_button"
}, {
    pId: 201,
    text: "bi.image_button",
    value: "demo.image_button"
}, {
    pId: 2,
    id: 202,
    text: "editor"
}, {
    pId: 202,
    text: "bi.editor",
    value: "demo.editor"
}, {
    pId: 202,
    text: "bi.code_editor",
    value: "demo.code_editor"
}, {
    pId: 202,
    text: "bi.multifile_editor",
    value: "demo.multifile_editor"
}, {
    pId: 202,
    text: "bi.textarea_editor",
    value: "demo.textarea_editor"
}, {
    pId: 202,
    text: "bi.formula_editor",
    value: "demo.formula_editor"
},

    {
        pId: 2,
        id: 5,
        text: "组合控件"
    }, {
        pId: 2,
        id: 8,
        text: "树控件"
    }, {
        pId: 2,
        id: 7,
        text: "按钮"
    }, {
        pId: 2,
        id: 9,
        text: "listitem"
    }, {
        pId: 2,
        text: "bi.canvas",
        value: "demo.canvas"
    }, {
        pId: 2,
        text: "bi.collection",
        value: "demo.collection"
    }, {
        pId: 2,
        text: "bi.farbtastic",
        value: "demo.farbtastic"
    }, {
        pId: 2,
        text: "bi.message",
        value: "demo.message"
    }, {
        pId: 2,
        text: "bi.grid_view",
        value: "demo.grid_view"
    }, {
        pId: 2,
        id: 6,
        text: "弹出层"
    }, {
        pId: 2,
        text: "bi.pager",
        value: "demo.pager"
    }, {
        pId: 2,
        text: "bi.svg",
        value: "demo.svg"
    }, {
        pId: 2,
        text: "bi.table",
        value: "demo.table"
    }, {
        pId: 5,
        text: "bi.combo",
        value: "demo.combo"
    }, {
        pId: 5,
        text: "bi.expander",
        value: "demo.expander"
    }, {
        pId: 5,
        text: "bi.group_button",
        value: "demo.group_button"
    }, {
        pId: 5,
        text: "bi.group_combo",
        value: "demo.group_combo"
    }, {
        pId: 5,
        text: "bi.loader",
        value: "demo.loader"
    }, {
        pId: 5,
        text: "bi.navigation",
        value: "demo.navigation"
    }, {
        pId: 5,
        text: "bi.searcher",
        value: "demo.searcher"
    }, {
        pId: 5,
        text: "bi.switcher",
        value: "demo.switcher"
    }, {
        pId: 5,
        text: "bi.tab",
        value: "demo.tab"
    }, {
        pId: 5,
        text: "bi.tree_button",
        value: "demo.tree_button"
    }, {
        pId: 6,
        text: "bi.layer_float_box",
        value: "demo.layer_float_box"
    }, {
        pId: 6,
        text: "bi.layer_popup",
        value: "demo.layer_popup"
    }, {
        pId: 6,
        text: "bi.layer_scroll",
        value: "demo.layer_scroll"
    }, {
        pId: 6,
        text: "bi.layer_searcher",
        value: "demo.layer_searcher"
    }, {
        pId: 8,
        text: "bi.treeview",
        value: "demo.treeview"
    }, {
        pId: 8,
        text: "bi.synctree",
        value: "demo.synctree"
    }, {
        pId: 8,
        text: "bi.parttree",
        value: "demo.parttree"
    }, {
        pId: 8,
        text: "bi.customtree",
        value: "demo.customtree"
    }, {
        pId: 9,
        text: "bi.list_items",
        value: "demo.list_items"
    },];