Demo.FIX_CONFIG = [{
    id: 7,
    text: "数据流框架fix-2.0"
}, {
    id: 71,
    pId: 7,
    text: "定义响应式数据",
    value: "demo.fix_define"
}, {
    id: 72,
    pId: 7,
    text: "state属性",
    value: "demo.fix_state"
}, {
    id: 73,
    pId: 7,
    text: "计算属性",
    value: "demo.fix_computed"
}, {
    id: 74,
    pId: 7,
    text: "store",
    value: "demo.fix_store"
}, {
    id: 75,
    pId: 7,
    text: "watcher且或表达式",
    value: "demo.fix_watcher"
}, {
    id: 76,
    pId: 7,
    text: "watcher星号表达式",
    value: "demo.fix_global_watcher"
}, {
    id: 77,
    pId: 7,
    text: "context",
    value: "demo.fix_context"
}, {
    id: 78,
    pId: 7,
    text: "一个混合的例子",
    value: "demo.fix"
}, {
    id: 79,
    pId: 7,
    text: "场景",
    value: "demo.fix_scene"
}, {
    id: 80,
    pId: 7,
    text: "inject",
    value: "demo.fix_inject"
}];
