Demo.WIDGET_CONFIG = [{
    id: 4,
    text: "详细控件",
    open: true
}, {
    pId: 4,
    id: 401,
    text: "各种小控件"
}, {
    pId: 401,
    text: "各种通用按钮",
    value: "demo.buttons"
}, {
    pId: 401,
    text: "各种提示性信息",
    value: "demo.tips"
}, {
    pId: 401,
    text: "各种items",
    value: "demo.items"
}, {
    pId: 401,
    text: "各种节点node",
    value: "demo.nodes"
}, {
    pId: 401,
    text: "各种segment",
    value: "demo.segments"
}, {
    pId: 4,
    id: 402,
    text: "文本框控件"
}, {
    pId: 402,
    text: "bi.text_editor",
    value: "demo.text_editor"
}, {
    pId: 402,
    text: "bi.search_editor",
    value: "demo.search_editor"
}, {
    pId: 402,
    text: "bi.number_editor",
    value: "demo.number_editor"
}, {
    pId: 4,
    id: 403,
    text: "tree"
}, {
    pId: 403,
    text: "bi.single_level_tree",
    value: "demo.single_level_tree"
}, {
    pId: 403,
    text: "bi.select_level_tree",
    value: "demo.select_level_tree"
}, {
    pId: 403,
    text: "bi.multilayer_single_level_tree",
    value: "demo.multilayer_single_level_tree"
}, {
    pId: 403,
    text: "bi.multilayer_select_level_tree",
    value: "demo.multilayer_select_level_tree"
}, {
    pId: 4,
    id: 405,
    text: "下拉列表"
}, {
    pId: 405,
    text: "bi.down_list_combo",
    value: "demo.down_list"
}, {
    pId: 4,
    id: 421,
    text: "单选下拉框"
}, {
    pId: 421,
    text: "bi.single_select_combo",
    value: "demo.single_select_combo"
}, {
    pId: 4,
    id: 406,
    text: "复选下拉框"
}, {
    pId: 406,
    text: "bi.multi_select_combo",
    value: "demo.multi_select_combo"
}, {
    pId: 406,
    text: "bi.multi_select_list",
    value: "demo.multi_select_list"
}, {
    pId: 4,
    id: 407,
    text: "简单下拉树"
}, {
    pId: 407,
    text: "bi.single_tree_combo",
    value: "demo.single_tree_combo"
}, {
    pId: 4,
    id: 408,
    text: "多层级下拉树"
}, {
    pId: 408,
    text: "bi.multilayer_single_tree_combo",
    value: "demo.multilayer_single_tree_combo"
}, {
    pId: 4,
    id: 409,
    text: "可选下拉树"
}, {
    pId: 409,
    text: "bi.select_tree_combo",
    value: "demo.select_tree_combo"
}, {
    pId: 4,
    id: 410,
    text: "多层级可选下拉树"
}, {
    pId: 410,
    text: "bi.multilayer_select_tree_combo",
    value: "demo.multilayer_select_tree_combo"
}, {
    pId: 4,
    id: 411,
    text: "复选下拉树"
}, {
    pId: 411,
    text: "bi.multi_tree_combo",
    value: "demo.multi_tree_combo"
}, {
    pId: 411,
    text: "bi.multi_select_tree",
    value: "demo.multi_select_tree"
}, {
    pId: 4,
    id: 412,
    text: "日期相关控件"
}, {
    pId: 412,
    text: "bi.year_combo",
    value: "demo.year"
}, {
    pId: 412,
    text: "bi.year_month_combo",
    value: "demo.year_month_combo"
}, {
    pId: 412,
    text: "bi.year_quarter_combo",
    value: "demo.year_quarter_combo"
}, {
    pId: 412,
    text: "bi.date_pane",
    value: "demo.date_pane"
}, {
    pId: 412,
    text: "bi.multidate_combo",
    value: "demo.multidate_combo"
}, {
    pId: 412,
    text: "bi.date_time",
    value: "demo.date_time"
}, {
    pId: 412,
    text: "bi.time_combo",
    value: "demo.time_combo"
}, {
    pId: 412,
    text: "bi.time_interval",
    value: "demo.time_interval"
}, {
    pId: 412,
    text: "bi.year_month_interval",
    value: "demo.year_month_interval"
}, {
    pId: 412,
    text: "bi.year_quarter_interval",
    value: "demo.year_quarter_interval"
}, {
    pId: 412,
    text: "bi.year_interval",
    value: "demo.year_interval"
}, {
    pId: 4,
    id: 413,
    text: "数值区间控件"
}, {
    pId: 413,
    text: "bi.number_interval",
    value: "demo.number_interval"
}, {
    id: 420,
    text: "滚动sliders",
    value: "demo.slider"
}, {
    pId: 4,
    id: 414,
    text: "折叠面板"
}, {
    pId: 414,
    text: "bi.collapse",
    value: "demo.collapse"
}];