Demo.WIDGET_CONFIG = [{
    id: 4,
    text: "详细控件",
    open: true
}, {
    pId: 4,
    id: 420,
    text: '各种小控件'
}, {
    pId: 420,
    text: "各种通用按钮",
    value: "demo.buttons"
}, {
    pId: 420,
    text: "各种提示性信息",
    value: "demo.tips"
}, {
    pId: 420,
    text: "各种items",
    value: "demo.items"
}, {
    pId: 420,
    text: "各种节点node",
    value: "demo.nodes"
}, {
    pId: 420,
    text: "各种segment",
    value: "demo.segments"
}, {
    pId: 420,
    text: "可以切换的树",
    value: "demo.switch_tree"
}, {
    id: 400,
    pId: 4,
    text: "tree"
}, {
    pId: 400,
    text: "bi.multi_tree_combo",
    value: "demo.multi_tree_combo"
}, {
    pId: 400,
    text: "bi.switch_tree",
    value: "demo.switch_tree"
}, {
    id: 401,
    pId: 4,
    text: "table"
}, {
    pId: 401,
    text: "bi.preview_table",
    value: "demo.preview_table"
}, {
    pId: 401,
    text: "bi.responsive_table",
    value: "demo.responsive_table"
}, {
    pId: 401,
    text: "bi.excel_table",
    value: "demo.excel_table"
}, {
    pId: 4,
    id: 402,
    text: "年份控件",
    open: false
}, {
    pId: 402,
    text: "bi.year_combo",
    value: "demo.year"
}, {
    pId: 4,
    id: 403,
    text: "月份控件",
    open: false
}, {
    pId: 403,
    text: "bi.month_combo",
    value: "demo.month"
}, {
    pId: 4,
    id: 404,
    text: "季度控件",
    open: false
}, {
    pId: 404,
    text: "bi.quarter_combo",
    value: "demo.quarter"
}, {
    pId: 4,
    id: 405,
    text: "下拉列表",
    open: false
}, {
    pId: 405,
    text: "bi.down_list_combo",
    value: "demo.down_list"
}, {
    pId: 4,
    id: 406,
    text: "文本框控件",
    open: false
}, {
    pId: 406,
    text: "bi.text_editor",
    value: "demo.text_editor"
}, {
    pId: 406,
    text: "bi.search_editor",
    value: "demo.search_editor"
}, {
    pId: 406,
    text: "bi.clear_editor",
    value: "demo.clear_editor"
}, {
    pId: 4,
    id: 407,
    text: "下拉框控件",
    open: false
}, {
    pId: 407,
    text: "bi.text_value_combo",
    value: "demo.text_value_combo"
}, {
    pId: 407,
    text: "bi.text_value_check_combo",
    value: "demo.text_value_check_combo"
}, {
    pId: 407,
    text: "bi.text_value_down_list_combo",
    value: "demo.text_value_down_list_combo"
}, {
    pId: 407,
    text: "bi.static_combo",
    value: "demo.static_combo"
}, {
    pId: 407,
    text: "bi.icon_combo",
    value: "demo.icon_combo"
}, {
    pId: 407,
    text: "bi.formula_combo",
    value: "demo.formula_combo"
}, {
    pId: 4,
    id: 410,
    text: "数值区间控件"
}, {
    pId: 410,
    text: "bi.numerical_interval",
    value: "demo.numberical_interval"
}, {
    pId: 4,
    id: 411,
    text: "下拉复选框有确定按钮"
}, {
    pId: 411,
    text: "bi.multi_select_combo",
    value: "demo.multi_select_combo"
}, {
    pId: 4,
    id: 412,
    text: "简单日期控件"
}, {
    pId: 412,
    text: "bi.date_combo",
    value: "demo.date"
}, {
    pId: 412,
    text: "bi.date_pane_widget",
    value: "demo.date_pane_widget"
}, {
    pId: 412,
    text: "bi.year_month_combo",
    value: "demo.year_month_combo"
}, {
    pId: 412,
    text: "bi.year_quarter_combo",
    value: "demo.year_quarter_combo"
}, {
    pId: 412,
    text: "bi.custom_date_time",
    value: "demo.custom_date_time"
}, {
    pId: 4,
    id: 413,
    text: "简单下拉树"
}, {
    pId: 413,
    text: "bi.single_tree_combo",
    value: "demo.single_tree_combo"
}, {
    pId: 413,
    text: "bi.multilayer_single_tree_combo",
    value: "demo.multilayer_single_tree_combo"
}, {
    pId: 4,
    id: 414,
    text: "可选下拉树"
}, {
    pId: 414,
    text: "bi.select_tree_combo",
    value: "demo.select_tree_combo"
}, {
    pId: 414,
    text: "bi.multilayer_select_tree_combo",
    value: "demo.multilayer_select_tree_combo"
}, {
    pId: 4,
    id: 415,
    text: "路径选择"
}, {
    pId: 415,
    text: "bi.path_chooser",
    value: "demo.path_chooser"
}, {
    pId: 415,
    text: "bi.direction_path_chooser",
    value: "demo.direction_path_chooser"
}, {
    pId: 4,
    id: 416,
    text: "关联视图"
}, {
    pId: 416,
    text: "bi.relation_view",
    value: "demo.relation_view"
}, {
    pId: 4,
    id: 417,
    text: "布局"
}, {
    pId: 417,
    text: "bi.adaptive_arrangement",
    value: "demo.adaptive_arrangement"
}, {
    pId: 417,
    text: "bi.interactive_arrangement",
    value: "demo.interactive_arrangement"
}, {
    pId: 4,
    id: 418,
    text: "提示对话框"
}, {
    pId: 418,
    text: "bi.dialog",
    value: "demo.dialog"
}, {
    pId: 4,
    id: 419,
    text: "文件管理"
}, {
    pId: 419,
    text: "bi.file_manager",
    value: "demo.file_manager"
}, {
    pId: 4,
    id: 421,
    text: "滚动调节"
}, {
    pId: 421,
    text: "bi.slider",
    value: "demo.slider"
}, {
    pId: 4,
    text: '时间间隔',
    value: 'demo.time_interval'
}];