Demo = {
    version: 1.0
};


BI.servletURL = "";
BI.resourceURL = "resource/";
BI.i18n = {
    "BI-Basic_OK": "确定",
    "BI-Basic_Sure": "确定",
    "BI-Basic_Clears": "清空",
    "BI-Basic_Cancel": "取消",
    "BI-Basic_Time": "时间",
    "BI-Basic_Simple_Sunday": "日",
    "BI-Basic_Simple_Monday": "一",
    "BI-Basic_Simple_Tuesday": "二",
    "BI-Basic_Simple_Wednesday": "三",
    "BI-Basic_Simple_Thursday": "四",
    "BI-Basic_Simple_Friday": "五",
    "BI-Basic_Simple_Saturday": "六",
    "BI-Multi_Date_Year": "年",
    "BI-Multi_Date_Month": "月",
    "BI-Multi_Date_Quarter": "季度",
    "BI-Basic_Unrestricted": "无限制",
    "BI-Quarter_1": "第1季度",
    "BI-Quarter_2": "第2季度",
    "BI-Quarter_3": "第3季度",
    "BI-Quarter_4": "第4季度",
    "BI-Basic_Value": "值",
    "BI-Load_More": "加载更多",
    "BI-Select_All": "全选",
    "BI-No_More_Data": "无更多数据",
    "BI-No_Selected_Value": "没有可选项",
    "BI-Basic_Clear": "清除",
    "BI-Multi_Date_Relative_Current_Time": "相对当前时间",
    "BI-Multi_Date_Year_Prev": "年前",
    "BI-Multi_Date_Year_Next": "年后",
    "BI-Multi_Date_Year_Begin": "年初",
    "BI-Multi_Date_Year_End": "年末",
    "BI-Multi_Date_Quarter_Prev": "个季度前",
    "BI-Multi_Date_Quarter_Next": "个季度后",
    "BI-Multi_Date_Quarter_Begin": "季度初",
    "BI-Multi_Date_Quarter_End": "季度末",
    "BI-Multi_Date_Month_Prev": "个月前",
    "BI-Multi_Date_Month_Next": "个月后",
    "BI-Multi_Date_Month_Begin": "月初",
    "BI-Multi_Date_Month_End": "月末",
    "BI-Multi_Date_Week_Prev": "周前",
    "BI-Multi_Date_Week_Next": "周后",
    "BI-Multi_Date_Day_Prev": "天前",
    "BI-Multi_Date_Day_Next": "天后",
    "BI-Multi_Date_Today": "今天",
    "BI-Date_Trigger_Error_Text": "日期格式示例\\:2015-3-11",
    "BI-Year_Trigger_Invalid_Text": "请输入有效时间",
    "BI-Multi_Date_YMD": "年/月/日",
    "BI-Multi_Date_Week": "周",
    "BI-Multi_Date_Day": "天"
};